services:
  envoy:
    image: envoyproxy/envoy:v1.34.0
    depends_on:
      game:
        condition: service_started
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./envoy:/etc/envoy
    restart: always

  game:
    build:
      context: .
    restart: always

  deploy:
    build:
      context: .
      target: godot
    volumes:
    - ./game:/src/build/game
    working_dir: /src/build/game
    command: mkdir -p dist && godot --verbose --headless --export-release "Web" --path . ./dist/index.html

# CERTBOT

  certbot:
    image: certbot/certbot
    profiles:
    - certbot
    depends_on:
      acme-webserver:
        condition: service_started
    volumes:
    - ./certbot/www:/var/www/certbot:rw
    - ./certbot/conf:/etc/letsencrypt:rw

  acme-webserver:
    image: nginx:alpine
    profiles:
    - certbot
    volumes:
    - ./certbot/www:/usr/share/nginx/html:ro
