services:
  envoy:
    image: envoyproxy/envoy:v1.34.0
    depends_on:
      game:
        condition: service_started
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./envoy:/etc/envoy
    restart: always

  game:
    build:
      context: .
    restart: always

# CERTBOT

  certbot:
    image: certbot/certbot
    profiles:
    - certbot
    depends_on:
      acme-webserver:
        condition: service_started
    volumes:
    - ./certbot/www:/var/www/certbot:rw
    - ./certbot/conf:/etc/letsencrypt:rw

  acme-webserver:
    image: nginx:alpine
    profiles:
    - certbot
    volumes:
    - ./certbot/www:/usr/share/nginx/html:ro
