on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

permissions:
  contents: read


jobs:
  build:
    name: Build game
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - run: |
        docker compose run deploy
    - name: Check if secrets are available
      id: secrets-check
      run: |
        if [ -z "${{ secrets.NETLIFY_AUTH_TOKEN }}" ]; then
            echo "has_secrets=false" >> $GITHUB_OUTPUT
        else
            echo "has_secrets=true" >> $GITHUB_OUTPUT
        fi
    - name: Install Netlify CLI
      if: steps.secrets-check.outputs.has_secrets == 'true'
      run: npm install -g netlify-cli
    - name: Deploy to Netlify
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && steps.secrets-check.outputs.has_secrets == 'true'
      run: |
        netlify deploy --dir=game/dist --prod
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    - name: Preview in Netlify
      if: github.event_name == 'pull_request' && steps.secrets-check.outputs.has_secrets == 'true'
      run: |
        netlify deploy --dir=game/dist --json --message "Deploy preview for PR #${{ github.event.pull_request.number }}"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
