on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

permissions:
  contents: read


jobs:
  build:
    name: Build game
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - run: |
        docker compose run deploy
    - name: Install Netlify CLI
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      run: npm install -g netlify-cli
    - name: Deploy to Netlify
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      run: |
        netlify deploy --dir=game/dist --prod
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
